version: '3.8'

services:
  # app:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/recally_db
  #     - REDIS_URL=redis://redis:6379/0
  #     - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
  #     - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
  #     - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
  #   volumes:
  #     - ..:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: recally_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
